src/lists/urls.py
from django.urls import path

from lists import views

urlpatterns = [
    path("new", views.new_list, name="new_list"),
    path("<int:list_id>/", views.view_list, name="view_list"),
]

src/superlists/urls.py
from django.urls import include, path

from lists import views as list_views

urlpatterns = [
    path("", list_views.home_page, name="home"),
    path("lists/", include("lists.urls")),
]

src/lists/models.py
from django.db import models
from django.urls import reverse


class List(models.Model):
    def get_absolute_url(self):
        return reverse("view_list", args=[self.id])


class Item(models.Model):
    text = models.TextField(default="")
    list = models.ForeignKey(List, default=None, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("list", "text")
        ordering = ["id"]

    def __str__(self) -> str:
        return self.text

src/lists/forms.py
from django import forms
from django.core.exceptions import ValidationError

from lists.models import Item, List

EMPTY_ITEM_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "You've already got this in your list"


class ItemForm(forms.models.ModelForm):
    class Meta:
        model = Item
        fields = ("text",)
        widgets = {
            "text": forms.widgets.TextInput(
                attrs={
                    "placeholder": "Enter a to-do item",
                    "class": "form-control form-control-lg",
                }
            ),
        }
        error_messages = {"text": {"required": EMPTY_ITEM_ERROR}}

    def save(self, for_list: List) -> Item:
        self.instance.list = for_list
        return super().save()


class ExistingListItemForm(ItemForm):
    def __init__(self, for_list: List, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {"text": [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

    def save(self) -> Item:
        return forms.models.ModelForm.save(self)

src/lists/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect

from lists.forms import ItemForm, ExistingListItemForm
from lists.models import List


def home_page(request: HttpRequest) -> HttpResponse:
    return render(request, "home.html", {"form": ItemForm()})


def new_list(request: HttpRequest) -> HttpResponse:
    form = ItemForm(data=request.POST)
    if form.is_valid():
        nulist = List.objects.create()
        form.save(for_list=nulist)
        return redirect(nulist)
    else:
        return render(request, "home.html", {"form": form})


def view_list(request: HttpRequest, list_id: int) -> HttpResponse:
    our_list = List.objects.get(id=list_id)
    if request.method == "POST":
        form = ExistingListItemForm(for_list=our_list, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(our_list)
    else:
        form = ExistingListItemForm(for_list=our_list)
    return render(request, "list.html", {"list": our_list, "form": form})

src/lists/templates/base.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
    <head>
        <title>To-Do lists</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    </head>

    <body>
        <div class="container">
            <div class="row justify-content-center p-5 bg-body-tertiary rounded-3">
                <div class="col-lg-6 text-center">
                    <h1 class="display-1 mb-4">
                        {% block header_text %}{% endblock %}
                    </h1>

                    <form method="POST" action="{% block form_action %}{% endblock %}">
                        <input
                            id="id_text"
                            name="text"
                            class="form-control
                                   form-control-lg
                                   {% if form.errors %}is-invalid{% endif %}"
                            placeholder="Enter a to-do item"
                            value="{{ form.text.value }}"
                            aria-describedby="id_text_feedback"
                            required
                        />
                        {% csrf_token %}
                        {% if form.errors %}
                            <div id="id_text_freedback" class="invalid-feedback">
                                {{ form.errors.text.0 }}
                            </div>
                        {% endif %}
                    </form>
                </div>
            </div>

            <div class="row justify-content-center">
                <div class="col-lg-6">
                    {% block table %}
                    {% endblock %}
                </div>
            </div>

        </div>

        <script src="/static/lists.js"></script>
        <script>
            window.onload = () => {initialize("#id_text")};
        </script>
    </body>

</html>

src/lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}{% url 'new_list' %}{% endblock %}

src/lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{% block form_action %}{% url 'view_list' list.id %}{% endblock %}

{% block table %}
    <table class="table" id="id_list_table">
        {% for item in list.item_set.all %}
            <tr><td>{{forloop.counter }}: {{ item.text }}</td></tr>
        {% endfor %}
    </table>
{% endblock %}